// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cache.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CacheItem struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Ttl                  int32    `protobuf:"varint,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheItem) Reset()         { *m = CacheItem{} }
func (m *CacheItem) String() string { return proto.CompactTextString(m) }
func (*CacheItem) ProtoMessage()    {}
func (*CacheItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{0}
}

func (m *CacheItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheItem.Unmarshal(m, b)
}
func (m *CacheItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheItem.Marshal(b, m, deterministic)
}
func (m *CacheItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheItem.Merge(m, src)
}
func (m *CacheItem) XXX_Size() int {
	return xxx_messageInfo_CacheItem.Size(m)
}
func (m *CacheItem) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheItem.DiscardUnknown(m)
}

var xxx_messageInfo_CacheItem proto.InternalMessageInfo

func (m *CacheItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CacheItem) GetTtl() int32 {
	if m != nil {
		return m.Ttl
	}
	return 0
}

type CacheGet struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CacheGet) Reset()         { *m = CacheGet{} }
func (m *CacheGet) String() string { return proto.CompactTextString(m) }
func (*CacheGet) ProtoMessage()    {}
func (*CacheGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{1}
}

func (m *CacheGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheGet.Unmarshal(m, b)
}
func (m *CacheGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheGet.Marshal(b, m, deterministic)
}
func (m *CacheGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheGet.Merge(m, src)
}
func (m *CacheGet) XXX_Size() int {
	return xxx_messageInfo_CacheGet.Size(m)
}
func (m *CacheGet) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheGet.DiscardUnknown(m)
}

var xxx_messageInfo_CacheGet proto.InternalMessageInfo

func (m *CacheGet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type CacheSet struct {
	Key                  string     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Item                 *CacheItem `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CacheSet) Reset()         { *m = CacheSet{} }
func (m *CacheSet) String() string { return proto.CompactTextString(m) }
func (*CacheSet) ProtoMessage()    {}
func (*CacheSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_5fca3b110c9bbf3a, []int{2}
}

func (m *CacheSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CacheSet.Unmarshal(m, b)
}
func (m *CacheSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CacheSet.Marshal(b, m, deterministic)
}
func (m *CacheSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CacheSet.Merge(m, src)
}
func (m *CacheSet) XXX_Size() int {
	return xxx_messageInfo_CacheSet.Size(m)
}
func (m *CacheSet) XXX_DiscardUnknown() {
	xxx_messageInfo_CacheSet.DiscardUnknown(m)
}

var xxx_messageInfo_CacheSet proto.InternalMessageInfo

func (m *CacheSet) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *CacheSet) GetItem() *CacheItem {
	if m != nil {
		return m.Item
	}
	return nil
}

func init() {
	proto.RegisterType((*CacheItem)(nil), "proto.CacheItem")
	proto.RegisterType((*CacheGet)(nil), "proto.CacheGet")
	proto.RegisterType((*CacheSet)(nil), "proto.CacheSet")
}

func init() { proto.RegisterFile("cache.proto", fileDescriptor_5fca3b110c9bbf3a) }

var fileDescriptor_5fca3b110c9bbf3a = []byte{
	// 187 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4e, 0x4c, 0xce,
	0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x52, 0x3c, 0xc9, 0xf9, 0xb9,
	0xb9, 0xf9, 0x79, 0x10, 0x41, 0x25, 0x63, 0x2e, 0x4e, 0x67, 0x90, 0x1a, 0xcf, 0x92, 0xd4, 0x5c,
	0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20,
	0x08, 0x47, 0x48, 0x80, 0x8b, 0xb9, 0xa4, 0x24, 0x47, 0x82, 0x49, 0x81, 0x51, 0x83, 0x35, 0x08,
	0xc4, 0x54, 0x92, 0xe1, 0xe2, 0x00, 0x6b, 0x72, 0x4f, 0x2d, 0x01, 0xc9, 0x66, 0xa7, 0x56, 0x42,
	0x75, 0x80, 0x98, 0x4a, 0x4e, 0x50, 0xd9, 0x60, 0x6c, 0xb2, 0x42, 0x2a, 0x5c, 0x2c, 0x99, 0x25,
	0xa9, 0xb9, 0x60, 0xe3, 0xb8, 0x8d, 0x04, 0x20, 0xce, 0xd0, 0x83, 0xbb, 0x21, 0x08, 0x2c, 0x6b,
	0x14, 0xce, 0xc5, 0x0a, 0x16, 0x12, 0xd2, 0xe0, 0x62, 0x06, 0xd9, 0xc2, 0x8f, 0xac, 0xce, 0x3d,
	0xb5, 0x44, 0x0a, 0x43, 0xa3, 0x90, 0x0a, 0x17, 0x73, 0x40, 0x29, 0x9a, 0xca, 0xe0, 0xd4, 0x12,
	0x29, 0x1e, 0xa8, 0x80, 0x6b, 0x6e, 0x41, 0x49, 0x65, 0x12, 0x1b, 0x98, 0x63, 0x0c, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xde, 0xb7, 0xb0, 0xd9, 0x1a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CacheClient is the client API for Cache service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CacheClient interface {
	Get(ctx context.Context, in *CacheGet, opts ...grpc.CallOption) (*CacheItem, error)
	Put(ctx context.Context, in *CacheSet, opts ...grpc.CallOption) (*Empty, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) Get(ctx context.Context, in *CacheGet, opts ...grpc.CallOption) (*CacheItem, error) {
	out := new(CacheItem)
	err := c.cc.Invoke(ctx, "/proto.Cache/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Put(ctx context.Context, in *CacheSet, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/proto.Cache/Put", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CacheServer is the server API for Cache service.
type CacheServer interface {
	Get(context.Context, *CacheGet) (*CacheItem, error)
	Put(context.Context, *CacheSet) (*Empty, error)
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheGet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Cache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Get(ctx, req.(*CacheGet))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CacheSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Cache/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Put(ctx, req.(*CacheSet))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Cache_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Cache_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cache.proto",
}
