// Code generated by protoc-gen-go. DO NOT EDIT.
// source: set.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetSetRequest struct {
	Set                  string   `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSetRequest) Reset()         { *m = GetSetRequest{} }
func (m *GetSetRequest) String() string { return proto.CompactTextString(m) }
func (*GetSetRequest) ProtoMessage()    {}
func (*GetSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d650fd95c5da449, []int{0}
}

func (m *GetSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSetRequest.Unmarshal(m, b)
}
func (m *GetSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSetRequest.Marshal(b, m, deterministic)
}
func (m *GetSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSetRequest.Merge(m, src)
}
func (m *GetSetRequest) XXX_Size() int {
	return xxx_messageInfo_GetSetRequest.Size(m)
}
func (m *GetSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSetRequest proto.InternalMessageInfo

func (m *GetSetRequest) GetSet() string {
	if m != nil {
		return m.Set
	}
	return ""
}

type ModifySetRequest struct {
	Set                  string   `protobuf:"bytes,1,opt,name=set,proto3" json:"set,omitempty"`
	Item                 string   `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ModifySetRequest) Reset()         { *m = ModifySetRequest{} }
func (m *ModifySetRequest) String() string { return proto.CompactTextString(m) }
func (*ModifySetRequest) ProtoMessage()    {}
func (*ModifySetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d650fd95c5da449, []int{1}
}

func (m *ModifySetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifySetRequest.Unmarshal(m, b)
}
func (m *ModifySetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifySetRequest.Marshal(b, m, deterministic)
}
func (m *ModifySetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifySetRequest.Merge(m, src)
}
func (m *ModifySetRequest) XXX_Size() int {
	return xxx_messageInfo_ModifySetRequest.Size(m)
}
func (m *ModifySetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifySetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifySetRequest proto.InternalMessageInfo

func (m *ModifySetRequest) GetSet() string {
	if m != nil {
		return m.Set
	}
	return ""
}

func (m *ModifySetRequest) GetItem() string {
	if m != nil {
		return m.Item
	}
	return ""
}

type SetResponse struct {
	Items                []string `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetResponse) Reset()         { *m = SetResponse{} }
func (m *SetResponse) String() string { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()    {}
func (*SetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d650fd95c5da449, []int{2}
}

func (m *SetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetResponse.Unmarshal(m, b)
}
func (m *SetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetResponse.Marshal(b, m, deterministic)
}
func (m *SetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetResponse.Merge(m, src)
}
func (m *SetResponse) XXX_Size() int {
	return xxx_messageInfo_SetResponse.Size(m)
}
func (m *SetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetResponse proto.InternalMessageInfo

func (m *SetResponse) GetItems() []string {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*GetSetRequest)(nil), "proto.GetSetRequest")
	proto.RegisterType((*ModifySetRequest)(nil), "proto.ModifySetRequest")
	proto.RegisterType((*SetResponse)(nil), "proto.SetResponse")
}

func init() { proto.RegisterFile("set.proto", fileDescriptor_2d650fd95c5da449) }

var fileDescriptor_2d650fd95c5da449 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4e, 0x2d, 0xd1,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x8a, 0x5c, 0xbc, 0xee, 0xa9, 0x25,
	0xc1, 0xa9, 0x25, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x02, 0x5c, 0xcc, 0xc5, 0xa9,
	0x25, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x92, 0x05, 0x97, 0x80, 0x6f, 0x7e,
	0x4a, 0x66, 0x5a, 0x25, 0x3e, 0x55, 0x42, 0x42, 0x5c, 0x2c, 0x99, 0x25, 0xa9, 0xb9, 0x12, 0x4c,
	0x60, 0x21, 0x30, 0x5b, 0x49, 0x99, 0x8b, 0x1b, 0xac, 0xa7, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55,
	0x48, 0x84, 0x8b, 0x15, 0x24, 0x5c, 0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x19, 0x04, 0xe1, 0x18,
	0x6d, 0x60, 0xe4, 0x62, 0x0e, 0x4e, 0x2d, 0x11, 0x32, 0xe2, 0x62, 0x83, 0xb8, 0x44, 0x48, 0x04,
	0xe2, 0x44, 0x3d, 0x14, 0x87, 0x49, 0x09, 0x41, 0x45, 0x91, 0x4d, 0x34, 0xe7, 0xe2, 0x70, 0x4c,
	0x49, 0x09, 0xc9, 0x07, 0xe9, 0x12, 0x87, 0xca, 0xa3, 0xbb, 0x15, 0xab, 0x46, 0x1b, 0x2e, 0xde,
	0xa0, 0xd4, 0xdc, 0xfc, 0xb2, 0x54, 0xb7, 0xa2, 0xfc, 0x5c, 0x52, 0x75, 0x27, 0xb1, 0x81, 0x85,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x0e, 0x2f, 0x7c, 0x63, 0x4f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SetClient is the client API for Set service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SetClient interface {
	GetSet(ctx context.Context, in *GetSetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	AddToSet(ctx context.Context, in *ModifySetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	RemoveFromSet(ctx context.Context, in *ModifySetRequest, opts ...grpc.CallOption) (*SetResponse, error)
}

type setClient struct {
	cc *grpc.ClientConn
}

func NewSetClient(cc *grpc.ClientConn) SetClient {
	return &setClient{cc}
}

func (c *setClient) GetSet(ctx context.Context, in *GetSetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/proto.Set/GetSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setClient) AddToSet(ctx context.Context, in *ModifySetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/proto.Set/AddToSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *setClient) RemoveFromSet(ctx context.Context, in *ModifySetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, "/proto.Set/RemoveFromSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SetServer is the server API for Set service.
type SetServer interface {
	GetSet(context.Context, *GetSetRequest) (*SetResponse, error)
	AddToSet(context.Context, *ModifySetRequest) (*SetResponse, error)
	RemoveFromSet(context.Context, *ModifySetRequest) (*SetResponse, error)
}

func RegisterSetServer(s *grpc.Server, srv SetServer) {
	s.RegisterService(&_Set_serviceDesc, srv)
}

func _Set_GetSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetServer).GetSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Set/GetSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetServer).GetSet(ctx, req.(*GetSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Set_AddToSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifySetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetServer).AddToSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Set/AddToSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetServer).AddToSet(ctx, req.(*ModifySetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Set_RemoveFromSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifySetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SetServer).RemoveFromSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Set/RemoveFromSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SetServer).RemoveFromSet(ctx, req.(*ModifySetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Set_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Set",
	HandlerType: (*SetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSet",
			Handler:    _Set_GetSet_Handler,
		},
		{
			MethodName: "AddToSet",
			Handler:    _Set_AddToSet_Handler,
		},
		{
			MethodName: "RemoveFromSet",
			Handler:    _Set_RemoveFromSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "set.proto",
}
